name: Release Build

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!**.md"
      - "!**/ISSUE_TEMPLATE/**"
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
    outputs:
      version: ${{ steps.set-ver.outputs.version }}
      play: ${{ steps.check.outputs.play }}
      sign: ${{ steps.check.outputs.sign }}
    steps:
      - id: set-ver
        run: |
          # 增加分钟 (mm) 以避免同小时多次推送导致的标签冲突
          echo "version=$(date -d "8 hour" -u +3.%y.%m%d%H%M)" >> $GITHUB_OUTPUT
      - id: check
        run: |
          echo "sign=yes" >> $GITHUB_OUTPUT
          if [ ! -z "${{ secrets.SERVICE_ACCOUNT_JSON }}" ]; then
            echo "play=yes" >> $GITHUB_OUTPUT
          fi

  build:
    needs: prepare
    if: ${{ needs.prepare.outputs.sign }}
    strategy:
      matrix:
        product: [app]
        type: [release, releaseS]
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      product: ${{ matrix.product }}
      type: ${{ matrix.type }}
      VERSION: ${{ needs.prepare.outputs.version }}
      play: ${{ needs.prepare.outputs.play }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17

      - name: Clear 18PlusList.txt
        run: |
          echo "清空18PlusList.txt"
          echo "">$GITHUB_WORKSPACE/app/src/main/assets/18PlusList.txt

      - name: Release Apk Sign
        run: |
          echo -e "\n" >> gradle.properties
          echo RELEASE_KEY_ALIAS='legado' >> gradle.properties
          echo RELEASE_KEY_PASSWORD='gedoor_legado' >> gradle.properties
          echo RELEASE_STORE_PASSWORD='gedoor_legado' >> gradle.properties
          echo RELEASE_STORE_FILE='../.github/workflows/legado.jks' >> gradle.properties

      - name: Build With Gradle
        run: |
          if [ "${{ env.type }}" == 'release' ]; then
            typeName="标准版"
          else
            typeName="Beta版"
            sed "s/'.release'/'.releaseS'/" $GITHUB_WORKSPACE/app/build.gradle  -i
          fi
          echo "统一版本号"
          sed "/def version/c def version = \"${{ env.VERSION }}\"" $GITHUB_WORKSPACE/app/build.gradle  -i
          echo "开始${{ env.product }}$typeName构建"
          chmod +x gradlew
          ./gradlew assemble${{ env.product }}release --build-cache --parallel --daemon --warning-mode all

      - name: Organize the Files
        run: |
          if [ "${{ env.type }}" == 'release' ]; then
            typeName=""
          else
            typeName="_beta"
          fi
          mkdir -p ${{ github.workspace }}/apk/
          find ${{ github.workspace }}/app/build/outputs/apk/ -name "*.apk" -exec cp {} ${{ github.workspace }}/apk/ \;

          # Rename APKs
          for file in `find ${{ github.workspace }}/apk/ -maxdepth 1 -name "*.apk"`; do
            new_file="${{ github.workspace }}/apk/legado_app_${{ env.VERSION }}${typeName}.apk"
            if [ "$file" != "$new_file" ]; then
              mv "$file" "$new_file"
            fi
          done

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: legado_${{ env.product }}_${{ env.type }}
          path: ${{ github.workspace }}/apk/*.apk

      - name: Release
        if: ${{ env.product == 'app' }}
        uses: softprops/action-gh-release@v2
        with:
          name: legado_app_${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: ${{ github.workspace }}/apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

